apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: todo-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URL
          value: "mongodb://34.46.46.122:27017/Todo"
        - name: PORT
          value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: todo-app
spec:
  selector:
    app: todo-backend
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP

