apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: todo-app
  labels:
    app: todo-backend
spec:
  type: LoadBalancer
  selector:
    app: todo-backend   
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

